build:
	./gradlew clean build installDist

run-dist:
	./build/install/app/bin/app

try-example:
	./build/install/app/bin/app /Users/s.roman3455/Documents/IT/Education/Hexlet/Java_developer/Projects/java-project-71/app/src/main/resources/file1.json /Users/s.roman3455/Documents/IT/Education/Hexlet/Java_developer/Projects/java-project-71/app/src/main/resources/file2.json

.PHONY: build
